query getThemeData($slug: String) {
  themes(where: { slug: $slug }) {
    title
    shortTitle
    slug
    color
    teaser
    intro
    rectangularImage {
      url
    }
    visualisation {
      title
      description
      source
      image {
        url
      }
    }
    topStory {
      ... on ComponentSharedArticles {
        articles{
          slug
        }
      }
      ... on ComponentSharedPublications {
        publications {
          slug
        }
      }
      ... on ComponentSharedVideos {
        videos {
          slug
        }
      }
      ... on ComponentSharedInteractives {
        interactives{
          slug
        }
      }
    }
    featured {
      ... on ComponentSharedArticles {
        articles{
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedPublications {
        publications {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedVideos {
        videos {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedInteractives {
        interactives{
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedCollections {
        collections {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedDatasets {
        datasets {
          title
          teaser: description
          slug
          squareImage {
            url
          }
        }
      }
    }
    collections {
      title
      slug
    }
    combiPicture {
      smallerImage {
        url
      }
      biggerImage {
        url
      }
    }
  }
}
