query getThemeData($slug: String) {
  themes(where: { slug: $slug }) {
    title
    shortTitle
    slug
    teaser
    intro
    squareImage {
      url
    }
    rectangularImage {
      url
    }
    visualisation {
      title
      text
      source
      color
      image {
        url
        width
        height
      }
      altText
    }
    topStory {
      ... on ComponentSharedArticles {
        articles {
          slug
        }
      }
      ... on ComponentSharedPublications {
        publications {
          slug
        }
      }
      ... on ComponentSharedVideos {
        videos {
          slug
        }
      }
      ... on ComponentSharedInteractives {
        interactives {
          slug
        }
      }
    }
    featured {
      ... on ComponentSharedArticles {
        articles {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
            width
            height
          }
          rectangularImage {
            url
            width
            height
          }
        }
      }
      ... on ComponentSharedPublications {
        publications {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
            width
            height
          }
          rectangularImage {
            url
            width
            height
          }
        }
      }
      ... on ComponentSharedVideos {
        videos {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
            width
            height
          }
          rectangularImage {
            url
            width
            height
          }
        }
      }
      ... on ComponentSharedInteractives {
        interactives {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
            width
            height
          }
          rectangularImage {
            url
            width
            height
          }
        }
      }
      ... on ComponentSharedCollections {
        collections {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
            width
            height
          }
          rectangularImage {
            url
            width
            height
          }
        }
      }
      ... on ComponentSharedDatasets {
        datasets {
          title
          teaser
          slug
          squareImage {
            url
            width
            height
          }
          rectangularImage {
            url
            width
            height
          }
        }
      }
    }
    collections {
      title
      slug
      updated_at
    }
    combiPicture {
      smallerImage {
        url
      }
      biggerImage {
        url
      }
    }
    email
    phoneNumber
  }
}
