version: '3'

services:
  database:
    image: postgres
    container_name: os-db-acc
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    networks:
      - os-network
    expose:
      - 5432
    volumes:
      - cms_data:/var/lib/postgresql/data

  cms:
    image: registry.gitlab.com/os-amsterdam/website-onderzoek-en-statistiek/cms:latest-acc
    restart: unless-stopped
    container_name: os-cms-acc
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: os-db-acc
      DATABASE_PORT: 5432
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
    networks:
      - os-network
    ports:
      - 1337:1337
    volumes:
      - cms_files:/srv/cms/public/uploads
    depends_on:
      - database
    
  website:
    image: registry.gitlab.com/os-amsterdam/website-onderzoek-en-statistiek/website:latest-acc
    restart: unless-stopped
    container_name: os-website-acc
    networks:
      - os-network
    ports:
      - 3000:3000
    depends_on:
      - database
      - cms

volumes:
  cms_files:
  cms_data:

networks:
  os-network:
    name: os-network