version: '3'
services:
  postgres:
    image: postgres
    container_name: os-db
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - 5432:5432