version: '3'
services:
  postgres:
    image: postgres
    container_name: os-db
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432