query getPublicationData($slug: String) {
  publications(where: { slug: $slug }) {
    slug
    author
    title
    shortTitle
    intro
    body
    introduction
    results
    conclusion
    publicationDate
    publicationSource
    file {
      name
      url
      size
    }
    related {
      articles {
        title
        slug
      }
      publications {
        title
        slug
      }
      videos {
        title
        slug
      }
      links {
        text
        url
      }
    }
    coverImage {
      url
    }
    teaserImage {
      url
    }
    theme {
      title
      slug
    }
  }
}
