query getPublicationData($slug: String) {
  publications(where: { slug: $slug }) {
    slug
    author
    title
    shortTitle
    intro
    body
    introduction
    results
    conclusion
    publicationDate
    publicationSource
    file {
      name
      url
      size
    }
    coverImage {
      url
    }
    teaserImage {
      url
    }
    theme {
      title
      slug
    }
  }
}
