query getAppData {
  homepage {
    shortcuts {
      ... on ComponentSharedArticles {
        articles {
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedPublications {
        publications {
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedVideos {
        videos {
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedInteractives {
        interactives {
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedCollections {
        collections {
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedDatasets {
        datasets {
          title
          slug
        }
      }
    }
  }
}
