# Write your query or mutation here
query getHomepageData {
  homepage {
    largeFirstFeature
    featured {
      ... on ComponentSharedArticles {
        articles{
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedPublications {
        publications {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedVideos {
        videos {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedInteractives {
        interactives{
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedCollections {
        collections {
          title
          shortTitle
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
    ... on ComponentSharedDatasets {
      datasets {
        title
        teaser
        slug
        squareImage {
          url
        }
      }
    }
  }
  featuredCollections {
    ... on ComponentSharedCollections {
      collections {
        title
        shortTitle
        teaser
        slug
      }
    }
  }
  agenda {
    ... on ComponentSharedArticles {
        articles{
          title
          shortTitle
          slug
        }
      }
    }
  shortcuts {
      ... on ComponentSharedArticles {
        articles{
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedPublications {
        publications {
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedVideos {
        videos {
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedInteractives {
        interactives{
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedCollections {
        collections {
          title
          shortTitle
          slug
        }
      }
      ... on ComponentSharedDatasets {
        datasets {
          title
          slug
        }
      }
    }
  relatedSites {
      title
      path
    }
  }
  themes {
    title
    slug
  }
}