# Write your query or mutation here
query getHomepageData {
  homepage {
    seo {
      metaTitle
      metaDescription
      shareImage {
        url
      }
    }
    heroImage {
      url
    }
    incoming {
      ... on ComponentSharedFeatures {
#     ... on ComponentSharedArticles {
        articles{
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
      ... on ComponentSharedFeatures {
#     ... on ComponentSharedPublications {
        publications {
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
      ... on ComponentSharedFeatures {
#     ... on ComponentSharedVideos {
        videos {
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
    },
    features {
      ... on ComponentSharedFeatures {
 #    ... on ComponentSharedInteractives {
        interactives{
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
      ... on ComponentSharedFeatures {
 #    ... on ComponentSharedVideos {
        videos {
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
      ... on ComponentSharedFeatures {
#     ... on ComponentSharedCollections {
        collections {
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
    },
    collections {
      ... on ComponentSharedFeatures {
#     ... on ComponentSharedCollections {
        collections{
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
    }
  }
  themes {
    title
    slug
    teaserImage {
      url
    }
  }
}