# Write your query or mutation here
query getHomepageData {
  homepage {
    seo {
      metaTitle
      metaDescription
      shareImage {
        url
      }
    }
    heroImage {
      url
    }
    incoming {
      ... on ComponentSharedFeatures {
        articles{
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
    ... on ComponentSharedFeatures {
        publications {
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
      ... on ComponentSharedFeatures {
        videos {
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
      ... on ComponentSharedFeatures {
        interactives {
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
      ... on ComponentSharedFeatures {
        collections{
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
    },
    features {
      ... on ComponentSharedFeatures {
        interactives{
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
    ... on ComponentSharedFeatures {
        videos {
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
    },
    collections {
      ... on ComponentSharedFeatures {
        collections{
          title
          teaser
          slug
          teaserImage {
            url
          }
        }
      }
    }
  }
  themes {
    title
    slug
    teaserImage {
      url
    }
  }
}