query getCollectionData($slug: String) {
  collections(where: { slug: $slug }) {
    title
    shortTitle
    teaser
    intro
    squareImage {
      url
    }
    rectangularImage {
      url
    }
    featured {
      ... on ComponentSharedArticles {
        articles {
          title
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedPublications {
        publications {
          title
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedVideos {
        videos {
          title
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedInteractives {
        interactives {
          title
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedDatasets {
        datasets {
          title
          slug
          squareImage {
            url
          }
        }
      }
    }
    collectionItems {
      ... on ComponentSharedArticles {
        articles {
          title
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedPublications {
        publications {
          title
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedVideos {
        videos {
          title
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedInteractives {
        interactives {
          title
          teaser
          slug
          squareImage {
            url
          }
          rectangularImage {
            url
          }
        }
      }
      ... on ComponentSharedDatasets {
        datasets {
          title
          slug
          squareImage {
            url
          }
        }
      }
    }
    linkList {
      ... on ComponentSharedArticles {
        articles {
          title
          slug
        }
      }
      ... on ComponentSharedPublications {
        publications {
          title
          slug
        }
      }
      ... on ComponentSharedVideos {
        videos {
          title
          slug
        }
      }
      ... on ComponentSharedInteractives {
        interactives {
          title
          slug
        }
      }
      ... on ComponentSharedCollections {
        collections {
          title
          slug
        }
      }
      ... on ComponentSharedDatasets {
        datasets {
          title
          slug
        }
      }
      ... on ComponentSharedLinks {
        links {
          title
          path
        }
      }
    }
    email
    phoneNumber
    theme {
      title
      slug
    }
  }
}
