build server:
  stage: build
  script:
    - docker run -v $pwd/config:/etc/nginx/user_conf.d/ --name check-nginx-config -t -a stdout nginx:latest nginx -t | grep "test is successful" | wc -l
    - docker rm check-nginx-config
    - docker build -t $TAG_SERVER_LATEST ./server
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_SERVER_LATEST
  only:
    refs:
      - develop
      - main
    changes:
      - server/**/*
      - /*.yml
