query getVideoData($slug: String) {
  videos(where: { slug: $slug }) {
    publicationDate
    title
    shortTitle
    intro
    teaser
    teaserImage {
      url
    }
    videoFile {
      url
    }
    subtitleFile {
      url
    }
    subtitleDefault
    externalVideoSource
    externalEmbedSource
    related {
      articles {
        title
        slug
      }
      publications {
        title
        slug
      }
      videos {
        title
        slug
      }
      links {
        text
        url
      }
    }
    theme {
      title
      slug
    }
  }
}
