query getVideoData($slug: String) {
  videos(where: { slug: $slug }) {
    title
    shortTitle
    teaser
    squareImage {
      url
    }
    rectangularImage {
      url
    }
    publicationDate
    transcript
    intro
    body {
      ... on ComponentSharedText {
        id
        text
      }
      ... on ComponentSharedTextWithLinks {
        id
        text
        articles {
          title
          slug
        }
        publications {
          title
          slug
        }
        videos {
          title
          slug
        }
        interactives {
          title
          slug
        }
        collections {
          title
          slug
        }
        datasets {
          title
          slug
        }
        links {
          title
          path
        }
      }
      ... on ComponentSharedVisualisation {
        id
        variant
        color
        title
        text
        source
        altText
        image {
          url
          caption
          width
          height
        }
      }
    }
    videoFile {
      url
    }
    subtitleFile {
      url
    }
    wideVideo
    subtitleDefault
    externalVideoSource
    externalEmbedSource
    theme {
      title
      slug
    }
  }
}
