query getInteractiveData($slug: String) {
  interactives(where: { slug: $slug }) {
    slug
    title
    shortTitle
    teaser
    contentLink
    squareImage {
      url
    }
    rectangularImage {
      url
    }
    implementation
    contentLink
    theme {
      title
      slug
    }
  }
}
